
name: Build Base Image
on:
  push:
    paths:
      - "docker/gpu/base/**"

env:
  CUDA_BASE_REPO: cuda-go-python-base

jobs:
  build-base-image:
    strategy:
      matrix:
        cuda: [11.7,12.1]
        python: [ 3.9.13 ,3.11.7]
        golang: [1.20]
        ubuntu_os: [1804]
    runs-on: ubuntu-latest
    # 项目构建
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.IFLYOPENSOURCE }}
          password: ${{ secrets.DOCKER_SECRET }}


      - name: Py39 Build Docker Image -cuda-base
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/gpu/base/python3.9/cuda-${{ matrix.cuda }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.IFLYOPENSOURCE }}/${{env.CUDA_BASE_REPO}}:${{ matrix.cuda }}-${{ matrix.golang }}-${{ matrix.python }}-ubuntu${{ matrix.ubuntu_os }}



      - name: Py311 Build Docker Image -cuda-base
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/gpu/base/python3.11/cuda-${{ matrix.cuda }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.IFLYOPENSOURCE }}/${{env.CUDA_BASE_REPO}}:${{ matrix.cuda }}-${{ matrix.golang }}-${{ matrix.python }}-ubuntu${{ matrix.ubuntu_os }}

